# ----------------------------------------------------------------------------------
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - roles
      - pipelines/roles.yml
      - pipelines/steps/create-roles.yml

resources:
  pipelines:
    # Trigger this pipeline when management-groups-ci pipeline completes
    - pipeline: ManagementGroups
      source: management-groups-ci
      trigger: true
        # branches:
        #    include:
        #      - refs/heads/main



variables:
- name: devops-org-name
  value: ${{ replace(replace(variables['System.CollectionUri'], 'https://dev.azure.com/' , ''), '/', '') }}
- name: variable-template-file
  value: ${{ variables['devops-org-name'] }}-${{ variables['Build.SourceBranchName'] }}.yml
- template: ../config/variables/common.yml
- template: ../config/variables/${{ variables['variable-template-file'] }}

pool:
  vmImage: $[ variables.vmImage ]

stages:

- stage: DeployRoleStage
  displayName: Deploy Custom Roles Stage

  jobs:

  - job: CustomRolesJob
    displayName: Custom Roles Job

    steps:

    # Required due to https://github.com/Azure/bicep/issues/2243 or upgrade to AzCLI 2.22.1+
    - task: Bash@3
      displayName: Upgrade Azure CLI
      enabled: false
      inputs:
        targetType: 'inline'
        script: 'az upgrade -y'

    - template: templates/steps/create-roles.yml
      parameters:
        description: 'Create Custom Roles'
        workingDir: $(System.DefaultWorkingDirectory)/roles
        deployTemplates: [appops-devops, netops, secops, subscription-owner]
        deployOperation: ${{ variables['deployOperation'] }}